repos:
  # Black: auto-formats Python code for consistent style
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # quick sanity checks: if these fail, whole file isn't executed.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files


  # isort: automatically sorts import statements for consistency
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  # Flake8: lints Python code for style, errors, and complexity
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  # Local hook to prevent committing any .env files.
  - repo: local
    hooks:
      - id: block-env-files
        name: Block .env files
        language: python
        entry: "hooks/block_env.py"
        files: (^|/)\.env(\.[a-zA-Z0-9_-]+|$)
