[project]
name = "currencyconverter"
version = "0.1.0"
description = ""
authors = [
    {name = "Tony Narloch",email = "tnarloch@hotmail.co.uk"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "sphinx (<9)",
    "myst-parser (>=4.0.1,<5.0.0)",
    "sphinxcontrib-mermaid (>=1.2.3,<2.0.0)"
]

[tool.semantic_release]
version_source = "tag"
upload_to_pypi = false
branch = "main"


]
